### ISSUE TITLE
校友你好，方便上传或一下网安的培养计划吗？

### ISSUE THREAD

**Issue by mingluosunyi** [ma5hr00m/HDU-agu-course#1]
校友你好，方便上传或一下网安的培养计划吗？我是计院的，想学习一下网安的知识。

**Comment by usamikinoko** [comment]
感谢提议！已经上传2021级和2022级专业培养方案：[网络空间安全学院相关资料](https://github.com/ma5hr00m/HDU-agu-course/tree/main/%E7%BD%91%E7%BB%9C%E7%A9%BA%E9%97%B4%E5%AE%89%E5%85%A8%E5%AD%A6%E9%99%A2%E7%9B%B8%E5%85%B3%E8%B5%84%E6%96%99) 。
